import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Postman Collections — LintPDF Admin",
  description:
    "Download Postman v2.1 collections for the LintPDF API (full + tenant-only).",
};

/**
 * Admin-only Postman download landing page.
 *
 * Serves the pre-generated Postman v2.1 collections produced by
 * ``tools/generate_postman.py``. Both files live under
 * ``packages/app/public/postman/`` so Next serves them statically;
 * the regenerator script mirrors ``docs/postman/`` into the public
 * folder so there's a single source of truth.
 *
 * The "Full" collection covers every engine route (tenant + admin) and
 * is for internal use; the "Tenant" collection covers only the
 * tenant-facing surface and is what we hand to customers.
 */
export default function AdminPostmanPage() {
  return (
    <div className="min-h-screen">
      <div className="mb-4 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="font-display text-2xl font-bold">Postman Collections</h1>
          <p className="text-sm text-muted-foreground">
            Pre-generated Postman v2.1 collections for the LintPDF engine.
            Import either file into Postman, set the <code>API_KEY</code>{" "}
            environment variable, and send.
          </p>
        </div>
        <div className="flex gap-2 text-sm">
          <Link
            href="/dashboard/admin/swagger"
            className="rounded border px-3 py-1 hover:bg-muted"
          >
            Swagger (all routes)
          </Link>
          <a
            href="https://lintpdf.com/docs"
            target="_blank"
            rel="noreferrer"
            className="rounded border px-3 py-1 hover:bg-muted"
          >
            Public docs
          </a>
        </div>
      </div>

      <div className="mt-6 grid gap-4 md:grid-cols-2">
        <section className="rounded-lg border bg-card p-4">
          <h2 className="font-semibold">Full collection (admin + tenant)</h2>
          <p className="mt-1 text-sm text-muted-foreground">
            Every engine route, including the admin surface. Requires the
            <code className="ml-1">LINTPDF_ADMIN_API_KEY</code> to exercise
            <code className="ml-1">/admin/*</code> endpoints. Internal use
            only &mdash; do not hand to customers.
          </p>
          <a
            href="/postman/lintpdf-all.postman_collection.json"
            download="lintpdf-all.postman_collection.json"
            className="mt-3 inline-block rounded-md bg-primary px-3 py-1.5 text-sm font-medium text-primary-foreground hover:bg-primary/90"
          >
            Download full collection
          </a>
        </section>

        <section className="rounded-lg border bg-card p-4">
          <h2 className="font-semibold">Tenant collection</h2>
          <p className="mt-1 text-sm text-muted-foreground">
            Tenant-facing routes only. Safe to share with customers. Uses a
            tenant&rsquo;s{" "}
            <code>lpdf_live_...</code> API key via the{" "}
            <code>{"{{API_KEY}}"}</code> variable.
          </p>
          <a
            href="/postman/lintpdf-tenant.postman_collection.json"
            download="lintpdf-tenant.postman_collection.json"
            className="mt-3 inline-block rounded-md bg-primary px-3 py-1.5 text-sm font-medium text-primary-foreground hover:bg-primary/90"
          >
            Download tenant collection
          </a>
        </section>
      </div>

      <section className="mt-6 rounded-lg border bg-muted/30 p-4 text-sm">
        <h3 className="font-semibold">How to import</h3>
        <ol className="mt-2 list-decimal space-y-1 pl-5 text-muted-foreground">
          <li>
            Download one of the collections above (right-click &rarr; Save
            as&hellip; if your browser tries to render the JSON inline).
          </li>
          <li>
            In Postman: <strong>File &rarr; Import</strong>, drop the{" "}
            <code>.postman_collection.json</code> file.
          </li>
          <li>
            Open <strong>Environments</strong>, create one called{" "}
            <code>LintPDF</code>, and set <code>API_KEY</code> to your
            tenant&rsquo;s <code>lpdf_live_...</code> key (or{" "}
            <code>LINTPDF_ADMIN_API_KEY</code> for the full collection).
          </li>
          <li>
            Pick the environment in the top-right and send any request.
          </li>
        </ol>
        <p className="mt-2 text-xs text-muted-foreground">
          Collections are regenerated by{" "}
          <code>python tools/generate_postman.py</code>; the dashboard serves
          the same bytes from <code>packages/app/public/postman/</code>.
        </p>
      </section>
    </div>
  );
}
