import { CodeBlock } from "@/components/docs/CodeBlock";
import { Endpoint } from "@/components/docs/Endpoint";

export default function ApiReferencePage() {
  return (
    <>
      <h2 className="text-2xl font-bold text-slate-900 mb-4">
        API Reference
      </h2>
      <p className="text-slate-600 mb-2">
        Base URL:{" "}
        <code className="bg-slate-100 px-1.5 py-0.5 rounded text-sm font-mono">
          https://api.lintpdf.com
        </code>
      </p>
      <p className="text-slate-500 text-sm mb-8">
        All endpoints return JSON. Authenticated endpoints require a valid
        API Key.
      </p>

      <Endpoint
        method="POST"
        path="/api/v1/submit"
        description="Submit a file for preflight analysis. Accepts PDF, EPS, PostScript, TIFF, JPEG, PNG, and PDF-compatible AI files. Non-PDF files are converted internally before checking."
        auth
        request={`curl -X POST https://api.lintpdf.com/api/v1/submit \\
  -H "Authorization: Bearer lpdf_..." \\
  -F file=@document.pdf \\
  -F ruleset=gwg-sheetfed`}
        response={`{
  "id": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
  "status": "processing",
  "ruleset": "gwg-sheetfed",
  "file_name": "document.pdf",
  "created_at": "2026-03-15T10:30:00Z"
}`}
      />

      <Endpoint
        method="GET"
        path="/api/v1/reports/{id}"
        description="Retrieve the Report for a completed preflight job. Includes summary, findings with severity levels (Error, Warning, Info), and page locations."
        auth
        request={`curl https://api.lintpdf.com/api/v1/reports/f47ac10b-... \\
  -H "Authorization: Bearer lpdf_..."`}
        response={`{
  "id": "f47ac10b-...",
  "status": "complete",
  "verdict": "error",
  "ruleset": "gwg-sheetfed",
  "file_name": "document.pdf",
  "page_count": 4,
  "duration_ms": 1240,
  "summary": {
    "total_findings": 3,
    "error": 1,
    "warning": 1,
    "info": 1
  },
  "findings": [
    {
      "inspection_id": "font.not_embedded",
      "severity": "error",
      "message": "Font 'Helvetica' is not embedded",
      "page": 1
    },
    {
      "inspection_id": "color.spot_color_usage",
      "severity": "warning",
      "message": "Spot color 'PANTONE 185 C' found on page 2",
      "page": 2
    },
    {
      "inspection_id": "image.low_resolution",
      "severity": "info",
      "message": "Image at 150 DPI (minimum 300 DPI recommended)",
      "page": 3
    }
  ]
}`}
      />

      <Endpoint
        method="GET"
        path="/api/v1/reports/{id}/report?format=pdf|json|xml"
        description="Download the Report as a formatted report. PDF reports include tenant White Label (logo, colors, footer) when configured. JSON and XML are machine-readable."
        auth
        request={`# PDF report (white-labeled)
curl -o report.pdf \\
  "https://api.lintpdf.com/api/v1/reports/f47ac10b-.../report?format=pdf" \\
  -H "Authorization: Bearer lpdf_..."

# JSON report
curl "https://api.lintpdf.com/api/v1/reports/f47ac10b-.../report?format=json" \\
  -H "Authorization: Bearer lpdf_..."`}
        response={`200 OK
Content-Type: application/pdf (or application/json, application/xml)

# JSON format returns the same structure as GET /api/v1/reports/{id}
# PDF format returns a branded, downloadable report
# XML format returns a structured XML document`}
      />

      <Endpoint
        method="PUT"
        path="/api/v1/white-label"
        description="Configure white-label branding for PDF reports. Upload your logo, set brand colors, and customize the footer text. Available on Scale and Enterprise plans."
        auth
        request={`curl -X PUT https://api.lintpdf.com/api/v1/white-label \\
  -H "Authorization: Bearer lpdf_..." \\
  -H "Content-Type: application/json" \\
  -d '{
    "logo_url": "https://yourcompany.com/logo.png",
    "primary_color": "#1a365d",
    "company_name": "Acme Print Co.",
    "footer_text": "Preflight report generated by Acme Print Co."
  }'`}
        response={`{
  "white_label": {
    "logo_url": "https://yourcompany.com/logo.png",
    "primary_color": "#1a365d",
    "company_name": "Acme Print Co.",
    "footer_text": "Preflight report generated by Acme Print Co.",
    "updated_at": "2026-03-15T10:30:00Z"
  }
}`}
      />

      <Endpoint
        method="GET"
        path="/api/v1/rulesets"
        description="List available Rulesets (preflight profiles). Includes built-in profiles and any custom profiles created by your account."
        auth={false}
        request={"curl https://api.lintpdf.com/api/v1/rulesets"}
        response={`{
  "rulesets": [
    {
      "id": "gwg-sheetfed",
      "name": "GWG Sheetfed",
      "description": "Ghent Workgroup sheetfed offset standard",
      "checks": 196,
      "is_builtin": true
    },
    {
      "id": "gwg-digital",
      "name": "GWG Digital",
      "description": "Ghent Workgroup digital printing standard",
      "checks": 180,
      "is_builtin": true
    },
    {
      "id": "pdfx4",
      "name": "PDF/X-4",
      "description": "ISO 15930-7 PDF/X-4 conformance",
      "checks": 120,
      "is_builtin": true
    },
    {
      "id": "packaging",
      "name": "Packaging",
      "description": "Packaging-specific checks including barcode grading",
      "checks": 210,
      "is_builtin": true
    }
  ]
}`}
      />

      <Endpoint
        method="POST"
        path="/api/v1/rulesets"
        description="Create a custom Ruleset. Select which Checks to include and configure thresholds. Available on Growth plans and above."
        auth
        request={`curl -X POST https://api.lintpdf.com/api/v1/rulesets \\
  -H "Authorization: Bearer lpdf_..." \\
  -H "Content-Type: application/json" \\
  -d '{
    "name": "My Custom Plan",
    "description": "Custom checks for magazine production",
    "base": "gwg-sheetfed",
    "overrides": {
      "image.min_dpi": 300,
      "barcode.min_grade": "C",
      "color.allow_spot": true
    }
  }'`}
        response={`{
  "id": "fp_custom_abc123",
  "name": "My Custom Plan",
  "description": "Custom checks for magazine production",
  "checks": 196,
  "is_builtin": false,
  "created_at": "2026-03-15T10:30:00Z"
}`}
      />
    </>
  );
}
