import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { BetaProvider } from "@/components/BetaContext";

export const metadata: Metadata = {
  // metadataBase lets Next.js resolve relative og:image / twitter:image URLs
  // to absolute ones. Without it, Slack / iMessage / LinkedIn won't render
  // link previews because crawlers require absolute image URLs.
  metadataBase: new URL("https://lintpdf.com"),
  title: "LintPDF — PDF Preflight API | Preflights you won't hate.",
  description:
    "Detection-only PDF preflight engine. API-first. 600+ checks for fonts, color, images, transparency, PDF/X-1a, PDF/X-3, PDF/X-4, and PDF/A compliance. Visual annotated reports. Self-service pricing.",
  keywords:
    "PDF preflight API, PDF/X-4 validation, print-ready PDF check, prepress quality control, PDF preflight SaaS, preflight-as-a-service, web-to-print preflight, PDF linter",
  openGraph: {
    title: "LintPDF — PDF Preflight API | Preflights you won't hate.",
    description:
      "Detection-only PDF preflight engine. 600+ checks. PDF/X-1a, PDF/X-3, PDF/X-4, PDF/A, GWG 2022 compliance. Visual annotated reports. Zero file modifications.",
    type: "website",
    url: "https://lintpdf.com",
    siteName: "LintPDF",
    // The actual image bytes are generated by src/app/opengraph-image.tsx
    // (Next.js file-based OG convention). We still list it here so Next
    // also emits og:image:width / og:image:height, which some unfurlers
    // (Slack especially) need before they'll show a preview card.
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "LintPDF — PDF Preflight API with 600+ checks",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "LintPDF — PDF Preflight API",
    description:
      "Detection-only PDF preflight engine. 600+ checks. PDF/X-1a, PDF/X-3, PDF/X-4, PDF/A compliance. Visual annotated reports.",
    images: ["/twitter-image"],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white text-slate-900 antialiased">
        <BetaProvider>
          <Header />
          <div className="pt-16">{children}</div>
          <Footer />
        </BetaProvider>
      </body>
    </html>
  );
}
