[build]
builder = "DOCKERFILE"
dockerfilePath = "packages/app/Dockerfile"
watchPatterns = ["packages/app/**"]
noCache = true

[deploy]
numReplicas = 1
startCommand = "sh packages/app/scripts/startup.sh"
healthcheckPath = "/auth/login"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
